__author__ = 'Yifei'

HEADER_BYTES = [0x44, 0x58]
HEADER_OFFSET = 0
HEADER_LEN = len(HEADER_BYTES)

LENGTH_OFFSET = 0 + HEADER_LEN
LENGTH_LEN = 1

CHECKSUM_LEN = 2
CHECKSUM_OFFSET = LENGTH_OFFSET + LENGTH_LEN

ADDRESS_LEN = 1
ADDRESS_OFFSET = CHECKSUM_OFFSET + CHECKSUM_LEN

OPERAND_LEN = 1
OPERAND_OFFSET = ADDRESS_OFFSET + ADDRESS_LEN

PAYLOAD_OFFSET = OPERAND_OFFSET + OPERAND_LEN

MAX_PAYLOAD_LENGTH = (128 - OPERAND_LEN - ADDRESS_LEN)

MIN_PACKET_LENGTH = ADDRESS_OFFSET

INVALID_ADDRESS = [0x00, 0xFF]

